### ISSUE TITLE
Sync Commands Error

### ISSUE THREAD

**Issue by CDE90** [CDESamBotDev/VCRoles#17]
Error occurs when sync commands task (from cogs/synccommands.py) runs.

To do with command registering using guild_only commands in addition to global commands.

```
Unhandled exception in internal background task 'synccommands'.
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 178, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/cogs/synccommands.py", line 13, in synccommands
    await self.client.register_commands()
  File "/home/container/.local/lib/python3.9/site-packages/discord/bot.py", line 323, in register_commands
    to_update = update_guild_commands[guild_id]
KeyError: 775477268893270027
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.9/site-packages/discord/bot.py", line 758, in on_connect
    await self.register_commands()
  File "/home/container/.local/lib/python3.9/site-packages/discord/bot.py", line 323, in register_commands
    to_update = update_guild_commands[guild_id]
KeyError: 775477268893270027
```

**Comment by CDE90** [comment]
Closing as #21 is more relevant
